build_boot_bin.sh: use vitis commands to generate the fsbl
After finding a bug in the mmi generation script in vivado 2020.1, I decided
it's time to move to the latest vivado/vitis release (2021.2). However,
installing Vitis using the Xilinx Unified installer requires hundreds
of GBs of disk space.

This is an attempt to make this repo work with the lightweight (10GB) xsct
archive used by meta-xilinx-tools, which can be downloaded from:
wget http://petalinux.xilinx.com/sswreleases/rel-v2021/xsct-trim/xsct-2021-2.tar.xz

The Vitis platform/app commands were crafted specifically to work in command
line mode only and not require a virtual display. Otherwise, the following
error would be generated:
ERROR: [#UNDEF] Java VM required by Vitis is not found in the Installatio

Signed-off-by: Ovidiu Panait <ovpanait@gmail.com>